name: Build Pebble Watchface

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Pebble Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pebble build environment
        uses: clach04/github_action_pebble_build@0.0.3
        with:
          # Optional: specify SDK version (default is SDK 4.5)
          sdk_version: 4.5

      - name: Build project
        run: |
          pebble build

      - name: Archive PBW
        uses: actions/upload-artifact@v4
        with:
          name: pebble-watchface
          path: build/*.pbw

  
          
