# From https://github.com/clach04/github_action_pebble_build/
name: PebbleBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for any branch (see commented out `branches` lines for  master branch example)
  push:
    branches: [master]
  pull_request:
    # External Pull Request requires confirmation BEFORE action fires https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks 
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # from https://levelup.gitconnected.com/how-to-manually-trigger-a-github-actions-workflow-4712542f1960
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Sanity checks for debugging, if/when problems occur
      - name: pyver
        run: python   --version
      - name: whichpy3
        run: which python3

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # from https://levelup.gitconnected.com/how-to-manually-trigger-a-github-actions-workflow-4712542f1960
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - uses: actions/setup-node@v2
      #- name: apt-getsudo
      #  run: apt-get update; apt-get -qq install -y sudo

      - name: apt-get
        run: sudo apt-get update && sudo apt-get install -y curl ca-certificates git python3-pip python3-venv nodejs npm libsdl1.2debian libsdl2-dev libfdt1 build-essential wget;
      - name: uv
        run: sudo mkdir -p /usr/local/uv && export UV_INSTALL_DIR=/usr/local/uv && export UV_UNMANAGED_INSTALL=/usr/local/uv && curl -LsSf https://astral.sh/uv/install.sh | sudo sh ln -s /usr/local/uv/uv /usr/local/bin/uv && sudo ln -s /usr/local/uv/uvx /usr/local/bin/uvx;
      - name: install pebble-tool
        run: uv tool install pebble-tool
      - name: pebble-build
        run: yes | sdk/bin/pebble build
      - name: Upload PBW
        uses: actions/upload-artifact@v4
        with:
          name: PebblePBW
          path: ./**/*.pbw
